### PR TITLE
Calender controller introduced

### PR DESCRIPTION
**Pull request by sayantanhore**
A file 'calender.js' is introduced. This file will hold all calendar related operation and will call 'CoapClient.js', with proper set of parameters.

### CODE REVIEW

**Comment by temmihoo** [comment]
Some boring technical notes:

the file calender.js should be calendar.js

the dependency to moment.js should be expressed in package.json

**Comment by sayantanhore** [comment]
I would probably add the finished events into a log file.

Currently there is no callback function attached to the events. The programme only prints to the console when an event starts or ends. Callback needs to be added.

**Comment by sayantanhore** [comment]
The problem with Gulp not waiting for Mocha timeout has been resolved. I was picking the Mocha parameters up in a wrong way, which would work only with Mocha run directly from the command line. Now it is working.

**Comment by sayantanhore** [comment]
The last few commits happened accidentally while checking pre-commit hook which failed from shell scripts.
Anyway, there is a question. We discussed that events can overlap, but is there any possibility of multiple events starting exactly at the same time? If so then we need to fix the code. The periodic check only starts the first event of those starting together. Because when it reaches the second and onwards, the moment has already passed. Therefore those are being skipped though not processed.

**Comment by sayantanhore** [comment]
The problem mentioned in the previous comment has been solved by changing the PeriodicTask delay to below 1000ms. Now it checks more than once before a second is passed and events starting at the same time (second wise) can be picked up. The unit test covers all possible 'Event.js' and 'Calendar.js' functions now as discussed. MochaJS tags are yet to be implemented.

**Pull request merged**
